name: Автодеплой на тестовый сервер
on:
  push:
    branches:
      - master

jobs:
  job-one:
    name: AutoDeploy
    runs-on: ubuntu-20.04
    steps:
      - name: Проверка подключения к серверу по SSH и сборка/запуск контейнеров Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WEB_LAB_HOST }}
          username: ${{ secrets.WEB_LAB_USERNAME }}
          port: ${{ secrets.WEB_LAB_PORT }}
          key: ${{ secrets.WEB_LAB_KEY }}
          script: |
            cd dev/StudentLib-WEB2
            git pull origin master
            git status
            cd docker
            docker-compose build && docker-compose up -d
